### ISSUE TITLE
credits

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [zaidmukaddam/realzaidmukaddam.tech#1]
Hi!

I randomly came across your profile and that you're using my portfolio as a template. You're allowed to use it for sure! but please leave some credits.. This is straight up copied, not even a little thing changed. Sad to see. 

Thanks Casper.

**Comment by zaidmukaddam** [comment]
Yeah Sure! I'll will add the credits! Sorry for the trouble and Thank you!
